[package]
name = "hiraku-script-derive"
description = "Registration macros for Hiraku Script native APIs"
version.workspace = true
edition.workspace = true
author.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"

[dependencies.syn]
version = "3.0.4"
features = ["full", "parsing"]