[package]
name = "hiraku-media"
description = "Hiraku media processing library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
crossbeam-channel = "0.5.16"

[dependencies.hiraku-opus]
git = "https://github.com/Hiraku-Project/opus-rs.git"
version = "0.1.32"

[dependencies.symphonia]
version = "0.6.1"
default-features = false
features = ["mkv"]

[target.'cfg(not(target_family = "wasm"))'.dependencies.hiraku-rav1d]
git = "https://github.com/Hiraku-Project/rav1d.git"
version = "1.1.0"

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3.104"
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"

[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3.104"
features = [
    "CanvasRenderingContext2d",
    "Document",
    "HtmlCanvasElement",
    "ImageData",
    "PlaneLayout",
    "VideoColorSpace",
    "VideoFrame",
    "VideoFrameCopyToOptions",
    "VideoMatrixCoefficients",
    "VideoPixelFormat",
    "VideoTransferCharacteristics",
    "Window",
]
