[workspace]
resolver = "2"
members = ["hiraku_engine", "hiraku_app", "hiraku_script", "hiraku_script_derive", "hiraku_cli", "hiraku_hdp", "hiraku_errors"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
event-listener = "5.4.2"
futures-lite = "2.6.1"
prost = "0.14.4"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
rustc-hash = "2.1.3"
bumpalo = "3.20.3"
uuid = "1"

hiraku-engine = { path = "hiraku_engine" }
hiraku-errors = { path = "hiraku_errors" }
hiraku-hdp = { path = "hiraku_hdp" }
hiraku-script = { path = "hiraku_script" }

[workspace.dependencies.bevy]
version = "0.19.1"
default-features = false
features = ["2d", "audio", "ui"]

[profile.app-release]
inherits = "release"
strip = true
lto = true
panic = "abort"
codegen-units = 1
