[package]
name = "hiraku"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0"
rand_pcg = "0.10.0"
prost = "0.14.3"
toml = "1.1.2"
thiserror = "2.0.18"
futures-lite = "2.6.1"
zip = "8.6.0"

[dependencies.bevy]
version = "0.18.1"
features = ["webp", "jpeg", "wav", "mp3", "flac"]

[dependencies.rhai]
version = "1.24.0"
features = ["serde"]

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[profile.app-release]
inherits = "release"
strip = true
lto = true
panic = "abort"
codegen-units = 1
