[package]
name = "hiraku-uastc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
basisu = { git = "https://github.com/Hiraku-Project/basisu", default-features = false, features = ["std"] }
thiserror.workspace = true
