[package]
name = "hiraku-storage"
description = "Hiraku multiplatform storage library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.91", features = ["Window", "Storage", "Event", "DomException", "IdbFactory", "IdbDatabase", "IdbOpenDbRequest", "IdbRequest", "IdbTransaction", "IdbTransactionMode", "IdbObjectStore"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
futures-channel = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
blocking = "1"

[dev-dependencies]
futures-lite.workspace = true
