[package]
name = "hiraku-storage"
description = "Hiraku multiplatform storage library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.91", features = ["Window", "Storage"] }
