[package]
name = "hiraku-hdp"
version.workspace = true
edition.workspace = true

[dependencies]
rayon = "1.12.0"
thiserror.workspace = true
zerocopy = { version = "0.8.56", features = ["derive"] }

[dependencies.zstd]
version = "0.13.3"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.zstd]
version = "0.13.3"
features = ["zstdmt"]
