[package]
name = "hiraku-engine"
description = "Hiraku visual-novel engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
hiraku-opus = { git = "https://github.com/Hiraku-Project/opus-rs.git", version = "0.1.32" }
ogg = "0.8"
rodio = { version = "0.22", default-features = false }
hiraku-uastc = { path = "../hiraku_uastc" }
hiraku-sprite3d = { path = "../hiraku_sprite3d" }
bevy.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
event-listener.workspace = true
futures-lite.workspace = true
hiraku-hdp.workspace = true
hiraku-errors.workspace = true
hiraku-script.workspace = true
hiraku-ui = { path = "../hiraku_ui" }
hiraku-storage.workspace = true
hiraku-video.workspace = true
prost.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
time.workspace = true
blake3 = "1"
rand_pcg.workspace = true

[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }
