[package]
name = "hiraku-engine"
version.workspace = true
edition.workspace = true
description = "Embeddable visual-novel runtime"

[dependencies]
bevy.workspace = true
event-listener.workspace = true
futures-lite.workspace = true
hiraku-hdp.workspace = true
hiraku-errors.workspace = true
hiraku-script.workspace = true
prost.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
time.workspace = true
rand_pcg.workspace = true