[package]
name = "hiraku-engine"
version.workspace = true
edition.workspace = true
description = "Embeddable visual-novel runtime"

[dependencies]
bevy.workspace = true
bevy_ui_render = "0.19"
futures-lite.workspace = true
hiraku-hdp.workspace = true
hiraku-script.workspace = true
prost.workspace = true
serde.workspace = true
thiserror.workspace = true
