[package]
name = "hiraku-script"
description = "Hiraku visual-novel scripting language"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
unicode-xid = "0.2.6"
unic-emoji-char = "0.9.0"
serde.workspace = true
rustc-hash.workspace = true
indexmap = "2.14.0"
bumpalo.workspace = true
hiraku-errors.workspace = true
hiraku-script-derive.workspace = true
