[package]
name = "hiraku-script"
version.workspace = true
edition.workspace = true
description = "Embeddable visual-novel scripting language"

[dependencies]
unicode-xid = "0.2.6"
unic-emoji-char = "0.9.0"
serde.workspace = true
rustc-hash.workspace = true
indexmap = "2.14.0"
hiraku-script-derive = { path = "../hiraku_script_derive" }
