[package]
name = "hiraku-app"
description = "Hiraku engine launcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "hiraku_app"
crate-type = ["lib", "cdylib"]

[dependencies]
bevy = { workspace = true, features = ["android-game-activity"] }
hiraku-engine.workspace = true
