name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write


env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    name: Build ${{ matrix.name }}

    strategy:
      fail-fast: false

      matrix:
        include:

          - name: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - name: linux-arm64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - name: linux-riscv64
            os: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu


          - name: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - name: windows-arm64
            os: windows-latest
            target: aarch64-pc-windows-msvc


          - name: macos-x64
            os: macos-latest
            target: x86_64-apple-darwin

          - name: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin


    runs-on: ${{ matrix.os }}


    steps:

      - name: Checkout
        uses: actions/checkout@v7


      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}


      # cross compile linux ARM/RISC-V
      - name: Install cross
        if: |
          matrix.name == 'linux-arm64' ||
          matrix.name == 'linux-riscv64'
        run: cargo install cross


      - name: Build
        shell: bash
        run: |
          if [[ "${{ matrix.name }}" == "linux-arm64" ||
                "${{ matrix.name }}" == "linux-riscv64" ]]
          then
            cross build \
              --release \
              --target ${{ matrix.target }}
          else
            cargo build \
              --release \
              --target ${{ matrix.target }}
          fi


      - name: Package
        shell: bash
        run: |
          mkdir -p dist

          if [[ "${{ matrix.name }}" == windows-* ]]; then
            EXT=".exe"
          else
            EXT=""
          fi

          cp \
            target/${{ matrix.target }}/release/hiraku-app${EXT} \
            dist/hiraku-app-${{ matrix.name }}${EXT}


      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: hiraku-${{ matrix.name }}
          path: dist/*



  release:

    name: Create Release

    needs: build

    runs-on: ubuntu-latest


    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/**/*